dist: xenial
language: node_js
os:
  - linux
node_js:
- 14
- 12
- 10
stages:
  - lint
  - test
  - deploy
install: if [ -z "$TRAVIS_TAG" ]; then npm install; fi
script: if [ -z "$TRAVIS_TAG" ]; then npm test; fi
after_success: if [ -z "$TRAVIS_TAG" ]; then npm run coverage; fi
jobs:
  include:
    - stage: lint
      if: tag IS blank
      install: npm install standard@14
      script: npm run lint
    - stage: deploy
      if: tag IS present
      node_js: 12
      install: skip
      script: skip
      deploy:
        provider: npm
        email: npmjs.org@kimminich.de
        api_token:
          secure: JzaeTe9fJeW5dXQ2rKibXJ+nVMpeESfoll9GsuLmDQEMstggEIwZdzPjf5mQLLCfdwrPflFuzG2pkmVsVatkZ4gmBVWK8Oq9DadF141S3i7ie2rH/fxTqeZEJRYb18KdyniOB6Z2KJkP9pCCRxNw+WEfaZKsBR9VrlZzV2P6104LCbbVL9UtfceisjNZZqTA27VR9yKWnoWHZ2uBegzUL7vO+KWnRLrFSoHHW+5qbZHrV/bVGaBWpx4p0EcgjuuIYNMA6SVRP5/UcjK9ayIhnqhqVqBIygw1IA5ZXaai8Jkx8bCeyKQA3+XUCCsP2lEq7hChy6WOZyaxJGjW6NqgYRYKh8Griyw5lLQwLYSO6OIWG+3+5bzCZ5UXsuKd2ILnstOvNJdLcrLobzElFgVIDelfWogpZyEALYypuNod+mJ+xBXVl5wjonSAd1h6vN21BvNObIGUW79r4tDW4rmDrHMPF5k4uzylKZGqg/LgsIjDQ7uaknEgNo2/uzUWQcGUPFjYMcWOXqBvIXsU3OpCWYx9cqULNIUb8DxUn0Xb2LjmPEbw3K4WC9MuT+TQjdymwL8NZMt0yaWUg7Mz4cTaPopwb0H3D0gdskppAO0UUcXIuVRsrh4V/F/vVIiWsAM7dH0A3zI1+JyH5c2U0Yyrz0QgDkdr/soQpUCBzYahGlo=
        on:
          repo: bkimminich/juicy-chat-bot
          tags: true
notifications:
  webhooks:
    urls:
      - secure: X24X0ujvR3PV6xsQBReIKtc+se+2v7QzCjfCXoyKQFCEtkAfK8yxIHq7OkWwW2tsuj9AxPnoNacgEPOZD+VVVs29VXpY8l+6T9XoBKFKMphOZSFLlS+zJnrjE4bFgrGB1RD2tJk1WNcPpql+ctXfscGvTqHhpSXvdwp/W67no7zo6aASwi4E+mLcJ0MWwcaAT3t0GUi9ZKRGcoQzADmjQspe8ONZ1EUS3KT3XjFaVbo2pTLmPsa+VJiHHdSJePUEo0sp1x9jl9xTnxxlB5yjxp8wT3FcJXA3gCDo5hWyv4Va0Gf+qZ/BdTmiYFmZoFS5qRZd5UZr9LptDRkKgYsMJdelMcuaKU/j8VGM24CFNTymAiW3YNxxO90gTOQpa+kW/V9OmnTV/QOaoaPNJqy4BdgrPEFGAbxURkA2jmzurnYIUm4rEOvsOi6LWSlbLHAnzDPglVc4YPdo1gZ/0mg62ZGX+afH/2fAQsR0FivwdcOSidtcdJTqsg9Z66KFBvQ7aQUI4saAUmNuwvWeNX9HMtz92l42OzIErQ2A4syQhrnwebMOrj/vZC7vZIHfbEnNsEA9FLy/8aR6Xs10hE1TnatQjyEgGKoljwaI+QSZUHmaf4ztezpC9Fh28bTzILai+wIM0EmPbT5JO6zXCEgeNLgUOcrpm9eZ1hm+DEjM5gg=
    on_success: always
    on_failure: always
    on_start: never
  slack:
    rooms:
      - secure: f34G+4gXNr9ycDWAJHmNEFe5fT6sWNl9nf9Njv9ZG8m8AllzYHHq8BASGDaYntVkcLthtldOVp+XWa+XOqBCA/h1hhj7til4Ph4w5ZBTC6C9vSLWdSkdDh2QrNX6VgTGPzB8xdzcxUbVdafSHOfVum1OYGar8TQUmNWEJPdk59DKvo0MFHbcxWjbGZ7AyLHF1VONhroZD7CaM2Yen3rTqkVuc/Q4EN7BQlplmskA7VXaX3/HXlfgRMJ0n2KrkvcxPDCrvcsciG7IHoAlNon7dtR5T6uhRuHeeCFCKd5Bvat7Ppv7IqoDFF0llbwpzjBiDY7ec4x/WUroYMVh1fNAYHqb+38p3NZOW8ESCbkruof1jTvtFmJDTSjD2YIIqbfcILOHHR7A7Y03pRO+XwIV0pK/mODXUOmRKIYl1e5Fb2I2VuSmzIQNCrIpTiwtjqjvUO9BtpXUYkKwHg1lSCZDFIZOCdJCG6gDV/2Rr4qujzkGC8IZ1BYIZh/fbFHHY7xf4szN5IIFDslcE24YSnHCwGlv/p3A2muH8qSSZltvYQA2FibtG0wz1Jhya9Cs9bduhIXYAinVQmjnARkmfh/mBkxxFBBKc77t3WeoeML2UqodWVuwMoBh8rMAlmiVWXFhkQLRkQUa/t9wTsVDUl/NQtxDXI/zx2OvjFa3tExsUQ0=
    on_success: change
    on_failure: change
    on_pull_requests: false
