dist: xenial
language: node_js
os:
  - linux
node_js:
- 14
- 12
- 10
stages:
  - lint
  - test
  - deploy
install: if [ -z "$TRAVIS_TAG" ]; then npm install; fi
script: if [ -z "$TRAVIS_TAG" ]; then npm test; fi
jobs:
  include:
    - stage: lint
      if: tag IS blank
      install: npm install standard@14
#      script: npm run lint
      script: echo "Linting disabled! Uncomment line above and delete this one to turn on!"
    - stage: deploy
      if: tag IS present
      node_js: 12
      install: skip
      script: skip
      deploy:
        provider: npm
        email: npmjs.org@kimminich.de
        api_token:
          secure: 6gKdwWsPRPlQaJZIEKtjlRZHLT2DjhVk9ZFIcHhG21euoIZ1bPlfPN4sbACUG7HXGZxN/YcRyx6djqeFprMe4OPyTTYNoZbOFJBKrViys84Tbui36m2sjo+sNsJokg1V0eDilsNGYg8v4yX+JVZzEvl6sT5ZUqn3WidlAqKEydR7tGxI/a9s9JYKQwKTcQi18HqIuBU/ro+GrTuCHrdEaMcE11GsO4fH0hDbXmL/qaEqWan4HGqLIKDg+UP+togJTceR+E6+lILHS/C52oyoRcVIBGVHYvrxLVQGCc2s+1vyzVUKV2SngOBrevggQWHCUWBPZXy9mqjjxEZJz8AwG5CdEU0pPKECJSgK8rXKgMrWaA+KCgX8YzAebCahTcRiAh5hVlZJcAPZbZNevzrD5qhB7AYVYIJGHdjDnEyZpYzQrkimtw2FAy7S5If4t3sE1Eu1kQ9rR3KHpdi1Jngp1hjhrvtQtvUCNgEF3FbKMRVnXZ3nF1AIjYxIxZDYRRGad9caO2kQ8ewRvFDx4c0YbYf4egwXEC+8psLTkv3+ixElcDcm9TJqhdM7JT/4O8aMyyY+AwH/N0sa8QGmrbS4jvEzKtLIYhyoD8JL09htJ2UmRsJtxTfCVaZAA6cQ1FLd31d6ZG1yhBSn9NIPc2Fe/ggwDw1RuA67VOg04iNXBkg=
        on:
          repo: bkimminich/juicy-chat-bot
          tags: true
notifications:
  webhooks:
    urls:
      - secure: "VFXBTxQKXD/TlZYTQ+zlDKnKZIIvcpEQdUeFWVuLgseI+L3IaUIEQ0gsxLI8qX+mg17D6uC/BgtYgcLaT0qE9GO1omYNQ6O6ZXfXq676SPek57AM7nqSc8HljvZ860JMbnlYX49xgP8fTFHAmk5Ar/b267UwHCQWdq/bBWXozQr0V5Hx2RaJdkM+VoL5QJq73QO8cSuxbYdmA6LoVgFrRkjqUHA9m83q2oE8ZlNyNRTo7j1Ev/G5lwnSKFc7YXRWrSxIYJaHGVCTMs0D8GC5xl6Fe7RbfhmV3aTKpm+ut7Pi4Nc96wLFn49ZQoNRf+5HJUrywhCdbDhKpgcdFdW1gomg2J9svTM7bkaxDjJvO8kT/om9ip0JZvp89/YVOXfagGE7j8gFYC5S1b71tnILmlJ9cQS0mu0GYUGu09MsJMbbRZU91oocruJcphSLvmsoPhtrQWf/WNO93jJBE3z1lGkS9WsSvZhalfFx/39cJTV4Oc1zXnheKnLgwXMtKv+873hzj0GSBXf34XetMETiYQN8xpSuxKEaeyA8F2mS92p+mnghsDrdn2MyPW4FqyWLifpV5sGgCylyWTVD5k7n8KmBhmNBsZNmgwKpQTVCX8GXruTL0wsI4m5saPF7+WgFzKw09n5mxeeEZcMcheB4LFehn39t+i6rgcdHlz3SSiA="
    on_success: always
    on_failure: always
    on_start: never
  slack:
    rooms:
      - secure: "1+a4LK0sykOq+NgvbB7L4OrchlGTvfsj6Ssfjnw1NgDghmY1UA+vuEt5Bc4EFa5h4yFh/T+A2go1cwz78dvAepTKouWkOHzbcefaZbg4+QpsSfohhMWdeGGUEasXpd5tBNRGExlpF7UKFy8osGcs6H3+fODPgup0irH3qX6/Q5Z0SGho0I6HYpptEQ8/ix8hlIIOdWpZsxf+oitYTbhc7G8ClZzCU6uT/dFIJFBzG1J5s8r2/cR6+jIY47sDe9uEqkmMHu9dFpAXJ1QI4pqZjtOQGq1r4lEpNop98RpNEekOPtYViPWO8cItE6ZqAp0+HeJMXshBz+KgwNAQLMGdXDZWMQGW6DXaRtgAty3I0ie7JtcE7vyZQ0hMUWkzJOmHheZ+TH8MdkPfdSha8bULTt4p7px2WtCi7yW3ZMYcRu49xMdZVJEzw41M1c9lRX+Y8Zh7KU9k61L5qeVaCkRx6tj0+ldr8rrKPzkvEm15rMRwinzcm59hdXkrzsNA+vJlQnkABzzDpf3ckkTs0TyoF89OYs2rdlsUwI3/lnF3Th8PViEmhOGf+W6A1+p63VR6RYnTXNlSDNfNN/ihoTk0o6MCskeJL0RxVL6O+JOExqnyQuiQdLw0rWeyycXJTSnAHw17RyoWIL8+RteJQMtRUggbodh4vKS3RrYRz5PGoHk="
    on_success: change
    on_failure: change
    on_pull_requests: false
