dist: xenial
language: node_js
os:
  - linux
node_js:
- 14
- 12
- 10
stages:
#  - lint
  - test
  - deploy
install: if [ -z "$TRAVIS_TAG" ]; then npm install; fi
script: if [ -z "$TRAVIS_TAG" ]; then npm test; fi
jobs:
  include:
#    - stage: lint
#      if: tag IS blank
#      install: npm install standard@14
#      script: npm run lint
    - stage: deploy
      if: tag IS present
      node_js: 12
      install: skip
      script: skip
      deploy:
        provider: npm
        email: npmjs.org@kimminich.de
        api_token:
          secure: 6gKdwWsPRPlQaJZIEKtjlRZHLT2DjhVk9ZFIcHhG21euoIZ1bPlfPN4sbACUG7HXGZxN/YcRyx6djqeFprMe4OPyTTYNoZbOFJBKrViys84Tbui36m2sjo+sNsJokg1V0eDilsNGYg8v4yX+JVZzEvl6sT5ZUqn3WidlAqKEydR7tGxI/a9s9JYKQwKTcQi18HqIuBU/ro+GrTuCHrdEaMcE11GsO4fH0hDbXmL/qaEqWan4HGqLIKDg+UP+togJTceR+E6+lILHS/C52oyoRcVIBGVHYvrxLVQGCc2s+1vyzVUKV2SngOBrevggQWHCUWBPZXy9mqjjxEZJz8AwG5CdEU0pPKECJSgK8rXKgMrWaA+KCgX8YzAebCahTcRiAh5hVlZJcAPZbZNevzrD5qhB7AYVYIJGHdjDnEyZpYzQrkimtw2FAy7S5If4t3sE1Eu1kQ9rR3KHpdi1Jngp1hjhrvtQtvUCNgEF3FbKMRVnXZ3nF1AIjYxIxZDYRRGad9caO2kQ8ewRvFDx4c0YbYf4egwXEC+8psLTkv3+ixElcDcm9TJqhdM7JT/4O8aMyyY+AwH/N0sa8QGmrbS4jvEzKtLIYhyoD8JL09htJ2UmRsJtxTfCVaZAA6cQ1FLd31d6ZG1yhBSn9NIPc2Fe/ggwDw1RuA67VOg04iNXBkg=
        on:
          repo: bkimminich/juicy-chat-bot
          tags: true
notifications:
  slack:
    rooms:
      secure: Y2azXvVSBBXkoTx1gNwZ3t4W8e3dDSlLuzn2sNnh1PCDmuBExecyYGJYUKGV4AXKg1uBqr8NAjSSfx7mbzLwZoIRsZaYl4R+Dbf1Q1ABch4zZUC7Ytonyicj5xbLm0QHs7SRYDG0rwZVMqSdR3bBZk2F5N48SpinVCc4ovDwa+m5q6IWhgNXVHBe2mOyTLpf+FMODJAE/VDk1HEjdcI4ErWzINRGw2K8WaKbt8gAf1mVDoZ84OjwvFxoqIOnmypItXKcb1FmSVjy4DyphvPpbuME93sGYeLV/jgZ0egD7J7qwrvL0BKNtA8FCbMF0OOyUnZCkegwdLMaWnrAj3pIQVYeZOSDQ5XRL0zqeTlT86o+Ywb1L1ROKQV/oyDH9xzYKKfVquqEy6fDImCxWglfG7iqI5eFtOjw/Dubo5eip5SG2N3XhhV3MbeSdxQYjwqE1oELrK2sq4dKMc1saHDXvdEALVj+ugobx3CPFm0z6h4gEoxC+TP9EvlIm97ZVLuAvZZiExD0fGV6weLBss8vT4p/ES/inIgz0z61pVG1Ly0eaPH+Bl/JIydrnBVKYtP7gVNtBKuuiHWqVuN1gRkwtXgt8hCpatw88IMDWQaTAAiKKp6kTrluzHbQBPBD838t/Ggx2Gx0xC7C5TAR1mB7nsHhpsl6onuY1frlMWF1fvQ=
    on_success: change
    on_failure: change
    on_pull_requests: false
